services:
  platform:
    image: pyronear/pyro-platform-react:latest
    container_name: platform
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - VITE_FILE_SITES_LIVE_ACCESS=sites_live_access.json
      - VITE_APP_CONFIG=app-config.js
    volumes:
      - ./public/config/sites_live_access_example.json:/usr/share/nginx/html/config/sites_live_access.json
      - ./public/config/app-config-dev.js:/usr/share/nginx/html/config/app-config.js
